DIAG(err_invalid_suffix, ::cci::Severity::Error, "invalid {0} suffix")
DIAG(warn_ucn_incomplete, ::cci::Severity::Warning, "incomplete universal character name; treating '\\' as an unknown token")
DIAG(err_ucn_invalid, ::cci::Severity::Error, "invalid universal character name; treating '\\' as an unknown token")
DIAG(err_line_comment_eof, ::cci::Severity::Error, "{0} comment doens't end in a {1}")
